### ISSUE TITLE
Add {JIM}: {JIM}

### ISSUE THREAD

**Issue by Diewomurashintaro** [zh/smartbch-token-list#10]
**Please provide the following information for your token.**

* Token Address: 
0xC46dC3CbDe96577A0E7e0C0221C2304FafEE0F5D
* Token Name (from contract): JIM
* Token Decimals (from contract): 18
* Token Symbol (from contract): JIM
* Token Image (URL): https://imgur.com/SvG0HNL

Link to the official homepage of token: http://www.jimtoken.web.id/?m=0

**Comment by zh** [comment]
Added in commit# 2c968c427c946bdeb160784819e2a47c93b6d45d
