### ISSUE TITLE
Add {MM}: {MoonMoon}

### ISSUE THREAD

**Issue by MoonMoonTG** [zh/smartbch-token-list#6]
**Please provide the following information for your token.**

* Token Address: 0x039Bcd43B18A29aa72CabFe269BA045447C881E4
* Token Name (from contract): MoonMoon
* Token Decimals (from contract): 18
* Token Symbol (from contract): MM
* Token Image (URL): https://i.gyazo.com/d77c3243caa5112d733ba4979ec51942.png

Link to the official homepage of token: https://moonmoon.dog/

**Comment by zh** [comment]
added to the list
