### ISSUE TITLE
Add {ForX}: {ForXtra}

### ISSUE THREAD

**Issue by Ab2thousand3** [zh/smartbch-token-list#7]
**Please provide the following information for your token.**

Token Address: 0xC595672b8eC5F27BB4078a7eF6382fb896aDD8E9
Token Name: ForXtra
Token Decimals (from contract): 9
Token Symbol: ForX
Token Image (URL): https://ibb.co/xgggK3s
Link to the official homepage of token: https://forxtra.com/

**Comment by zh** [comment]
not a smart contract address. looks as a scam.
