### ISSUE TITLE
Add {LILY}: {LILY FLOWER}

### ISSUE THREAD

**Issue by LILYFLOWERTOKEN** [zh/smartbch-token-list#8]
**Please provide the following information for your token.**

* Token Address: 0x5A0C102818d1EE4874d20eE035871bE259E353DD
* Token Name (from contract): LILY FLOWER
* Token Decimals (from contract): 18
* Token Symbol (from contract): LILY
* Token Image (URL): https://i.postimg.cc/tCWX32wK/64.png

Link to the official homepage of token: https://t.me/LILYFlowerToken

**Comment by zh** [comment]
Better token image: https://i.postimg.cc/tCWX32wK/64.png

**Comment by LILYFLOWERTOKEN** [comment]
ok it's been changed

**Comment by zh** [comment]
added to the list - https://zh.thedev.id/sep20tokens/
