### ISSUE TITLE
Add {JIM}: {JIM}

### ISSUE THREAD

**Issue by Diewomurashintaro** [zh/smartbch-token-list#9]
**Please provide the following information for your token.**

* Token Address: 
0xC46dC3CbDe96577A0E7e0C0221C2304FafEE0F5D
* Token Name (from contract): JIM
* Token Decimals (from contract): 18
* Token Symbol (from contract): JIM
* Token Image (URL): https://ibb.co/tXjN6DV

Link to the official homepage of token: https://t.me/Jimtokenofficial

**Comment by zh** [comment]
Replaced by [PR#10](https://github.com/zh/smartbch-token-list/issues/10)
